# Generated by Django 3.1.7 on 2021-05-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210327_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='texPrice',
            new_name='taxPrice',
        ),
    ]
