# Generated by Django 3.1.7 on 2021-05-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210509_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sheepingPrice',
            new_name='shippingPrice',
        ),
    ]
